apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t2t-mini-pvc
  namespace: cmsc828b
  labels:
    app: t2t-mini-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 48Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: t2t-mini
  namespace: cmsc828b
spec:
  template:
    metadata:
      labels:
        name: t2t-mini
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pingthings.io/role-compute
                operator: Exists
      restartPolicy: OnFailure
      containers:
      - name: t2t-mini
        imagePullPolicy: Always
        image: looselycoupled/cmsc828b-tensor2tensor
        command: ["./execute.sh"]
        args: []
        env:
        - name: TRAIN_DATASET
          value: mini
        - name: TRAIN_STEPS
          value: "1000"
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          value:
        - name: AWS_SECRET_ACCESS_KEY
          value:
        volumeMounts:
        - name: checkpoints
          mountPath: /project/checkpoints
        ports: []
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "32Gi"
          requests: {"cpu": "1", "memory": "32Gi"}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        persistentVolumeClaim:
          claimName: t2t-mini-pvc
