apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: train-batch64-len150-pvc
  namespace: cmsc828b
  labels:
    app: train-batch64-len150-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 48Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: train-batch64-len150
  namespace: cmsc828b
spec:
  template:
    metadata:
      labels:
        name: train-batch64-len150
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pingthings.io/role-compute
                operator: Exists
      restartPolicy: OnFailure
      containers:
      - name: train-batch64-len150
        imagePullPolicy: Always
        image: looselycoupled/cmsc828b-noise-simple
        command: ["./execute.sh"]
        args: []
        env:
        - name: TRAINING_FILE1
          value: data/baseline.tok.de
        - name: TRAINING_FILE2
          value: data/baseline.tok.en
        - name: BATCHSIZE
          value: "64"
        - name: MAXLENGTH
          value: "150"
        volumeMounts:
        - name: checkpoints
          mountPath: /project/checkpoints
        ports: []
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "40Gi"
          requests: {"cpu":"1","memory":"40Gi"}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        persistentVolumeClaim:
          claimName: train-batch64-len150-pvc