apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-pvc
  namespace: cmsc828b
  labels:
    app: sandbox-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  namespace: cmsc828b
spec:
  replicas: 1
  selector:
      matchLabels:
        name: sandbox
  template:
    metadata:
      labels:
        name: sandbox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pingthings.io/role-compute
                operator: Exists
      containers:
      - name: sandbox
        imagePullPolicy: Always
        image: looselycoupled/cmsc828b-noise-simple
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: TRAINING_FILE1
          value: baseline.tok.de
        - name: TRAINING_FILE2
          value: baseline.tok.en
        - name: BATCHSIZE
          value: "100"
        - name: MAXLENGTH
          value: "200"
        volumeMounts:
        - name: checkpoints
          mountPath: /project/checkpoints
        ports: []
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "40Gi"
          requests: {"cpu":"1","memory":"40Gi"}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        persistentVolumeClaim:
          claimName: sandbox-pvc