apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t2t-test-pvc
  namespace: cmsc828b
  labels:
    app: t2t-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 48Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: t2t-test
  namespace: cmsc828b
spec:
  template:
    metadata:
      labels:
        name: t2t-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pingthings.io/role-compute
                operator: Exists
      restartPolicy: OnFailure
      containers:
      - name: t2t-test
        imagePullPolicy: Always
        image: looselycoupled/cmsc828b-t2t-test
        command: ["./execute.sh"]
        args: []
        env:
        - name: TRAIN_DATASET
          value: mini
        volumeMounts:
        - name: checkpoints
          mountPath: /project/checkpoints
        ports: []
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "32Gi"
          requests: {"cpu":"1","memory":"32Gi"}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        persistentVolumeClaim:
          claimName: t2t-test-pvc