apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-alt-pvc
  namespace: cmsc828b
  labels:
    app: sandbox-alt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-alt
  namespace: cmsc828b
spec:
  replicas: 1
  selector:
      matchLabels:
        name: sandbox-alt
  template:
    metadata:
      labels:
        name: sandbox-alt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pingthings.io/role-compute
                operator: Exists
      containers:
      - name: sandbox-alt
        imagePullPolicy: Always
        image: tensorflow/tensorflow:1.15.2-gpu
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env: []
        volumeMounts:
        - name: checkpoints
          mountPath: /project/checkpoints
        ports: []
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "32Gi"
          requests: {"cpu":"1","memory":"32Gi"}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        persistentVolumeClaim:
          claimName: sandbox-alt-pvc