apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t2t-sandbox-pvc
  namespace: cmsc828b
  labels:
    app: t2t-sandbox-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t2t-sandbox
  namespace: cmsc828b
spec:
  replicas: 1
  selector:
      matchLabels:
        name: t2t-sandbox
  template:
    metadata:
      labels:
        name: t2t-sandbox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pingthings.io/role-compute
                operator: Exists
      containers:
      - name: t2t-sandbox
        imagePullPolicy: Always
        image: looselycoupled/cmsc828b-tensor2tensor
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: PROBLEM
          value: translate_noise
        - name: TRAIN_DATASET
          value: mini
        - name: TRAIN_STEPS
          value: "1000"
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          value:
        - name: AWS_SECRET_ACCESS_KEY
          value:
        volumeMounts:
        - name: checkpoints
          mountPath: /project/checkpoints
        ports: []
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "32Gi"
          requests: {"cpu":"1","memory":"32Gi"}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        persistentVolumeClaim:
          claimName: t2t-sandbox-pvc